# Generated by Django 4.2.11 on 2024-03-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='facturacompra',
            name='fecha',
        ),
    ]
