# Generated by Django 4.2.6 on 2023-10-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='nombre_categoria',
        ),
    ]
