# Generated by Django 4.2.6 on 2023-11-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_categoria_nombre_categoria_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img_productos', verbose_name='Imagen'),
        ),
    ]
