# Generated by Django 4.2.6 on 2023-11-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='img_productos', verbose_name='Imagen'),
        ),
    ]
